package n2xsdk

type OspfLsa struct {
 Handler string
}

func(np *OspfLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfLsa SetAdvertisingRouter, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfLsa GetAdvertisingRouter
 return "", nil
}

func(np *OspfLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfLsa SetLinkStateId, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfLsa GetLinkStateId
 return "", nil
}

func(np *OspfLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfLsa SetOptions, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfLsa GetOptions
 return "", nil
}

func(np *OspfLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfLsa SetLsType, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfLsa GetLsType
 return "", nil
}

func(np *OspfLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfLsa Advertise, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfLsa Withdraw, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfLsa GetAdvertiseFlag
 return "", nil
}

func(np *OspfLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfLsa EnableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfLsa DisableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfLsa IsFieldAutoGenerated, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfLsa SetChecksum, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfLsa GetChecksum
 return "", nil
}

func(np *OspfLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfLsa SetLsAge, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfLsa GetLsAge
 return "", nil
}

func(np *OspfLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfLsa SetSequenceNumber, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfLsa GetSequenceNumber
 return "", nil
}

func(np *OspfLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfLsa EnableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfLsa DisableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *OspfLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfLsa IsAutoUpdateEnabled, m.Object, m.Name);
 return nil
}

