package n2xsdk

type OspfOpaqueLsa struct {
 Handler string
}

func(np *OspfOpaqueLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfOpaqueLsa SetAdvertisingRouter
 return nil
}

func(np *OspfOpaqueLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa GetAdvertisingRouter
 return "", nil
}

func(np *OspfOpaqueLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfOpaqueLsa SetLinkStateId
 return nil
}

func(np *OspfOpaqueLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa GetLinkStateId
 return "", nil
}

func(np *OspfOpaqueLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfOpaqueLsa SetOptions
 return nil
}

func(np *OspfOpaqueLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa GetOptions
 return "", nil
}

func(np *OspfOpaqueLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfOpaqueLsa SetLsType
 return nil
}

func(np *OspfOpaqueLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfOpaqueLsa GetLsType
 return "", nil
}

func(np *OspfOpaqueLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa Advertise
 return nil
}

func(np *OspfOpaqueLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa Withdraw
 return nil
}

func(np *OspfOpaqueLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa GetAdvertiseFlag
 return "", nil
}

func(np *OspfOpaqueLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfOpaqueLsa EnableAutoGenerate
 return nil
}

func(np *OspfOpaqueLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfOpaqueLsa DisableAutoGenerate
 return nil
}

func(np *OspfOpaqueLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfOpaqueLsa IsFieldAutoGenerated
 return nil
}

func(np *OspfOpaqueLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfOpaqueLsa SetChecksum
 return nil
}

func(np *OspfOpaqueLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa GetChecksum
 return "", nil
}

func(np *OspfOpaqueLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfOpaqueLsa SetLsAge
 return nil
}

func(np *OspfOpaqueLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa GetLsAge
 return "", nil
}

func(np *OspfOpaqueLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfOpaqueLsa SetSequenceNumber
 return nil
}

func(np *OspfOpaqueLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa GetSequenceNumber
 return "", nil
}

func(np *OspfOpaqueLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa EnableAutoUpdate
 return nil
}

func(np *OspfOpaqueLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa DisableAutoUpdate
 return nil
}

func(np *OspfOpaqueLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa IsAutoUpdateEnabled
 return nil
}

func(np *OspfOpaqueLsa) SetOpaqueLsaType () error {
 //parameters: LsaHandle Type
 //AgtOspfOpaqueLsa SetOpaqueLsaType
 return nil
}

func(np *OspfOpaqueLsa) GetOpaqueLsaType ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa GetOpaqueLsaType
 return "", nil
}

func(np *OspfOpaqueLsa) AddTlv () error {
 //parameters: Count ExtendedHandle TlvType
 //AgtOspfOpaqueLsa AddTlv
 return nil
}

func(np *OspfOpaqueLsa) RemoveTlv () error {
 //parameters: Count ExtendedHandle
 //AgtOspfOpaqueLsa RemoveTlv
 return nil
}

func(np *OspfOpaqueLsa) ListTlvs ()(string, error) {
 //parameters: Count ExtendedHandle
 //AgtOspfOpaqueLsa ListTlvs
 return "", nil
}

func(np *OspfOpaqueLsa) GetTlvValueType ()(string, error) {
 //parameters: Count ExtendedHandle
 //AgtOspfOpaqueLsa GetTlvValueType
 return "", nil
}

func(np *OspfOpaqueLsa) SetTlvIpv4Address () error {
 //parameters: Count ExtendedHandle Ipv4Address
 //AgtOspfOpaqueLsa SetTlvIpv4Address
 return nil
}

func(np *OspfOpaqueLsa) GetTlvIpv4Address ()(string, error) {
 //parameters: Count ExtendedHandle
 //AgtOspfOpaqueLsa GetTlvIpv4Address
 return "", nil
}

func(np *OspfOpaqueLsa) SetTlvLong () error {
 //parameters: Count ExtendedHandle Length aLongValue
 //AgtOspfOpaqueLsa SetTlvLong
 return nil
}

func(np *OspfOpaqueLsa) GetTlvLong ()(string, error) {
 //parameters: Count ExtendedHandle
 //AgtOspfOpaqueLsa GetTlvLong
 return "", nil
}

func(np *OspfOpaqueLsa) SetTlvFloat () error {
 //parameters: Count ExtendedHandle aFloatValue
 //AgtOspfOpaqueLsa SetTlvFloat
 return nil
}

func(np *OspfOpaqueLsa) GetTlvFloat ()(string, error) {
 //parameters: Count ExtendedHandle
 //AgtOspfOpaqueLsa GetTlvFloat
 return "", nil
}

func(np *OspfOpaqueLsa) SetTlvFloatList ()(string, error) {
 //parameters: Count ExtendedHandle NumFloats aFloatList
 //AgtOspfOpaqueLsa SetTlvFloatList
 return "", nil
}

func(np *OspfOpaqueLsa) GetTlvFloatList ()(string, error) {
 //parameters: Count ExtendedHandle
 //AgtOspfOpaqueLsa GetTlvFloatList
 return "", nil
}

func(np *OspfOpaqueLsa) SetTlvHexList ()(string, error) {
 //parameters: Count ExtendedHandle NumOctets pHexList
 //AgtOspfOpaqueLsa SetTlvHexList
 return "", nil
}

func(np *OspfOpaqueLsa) GetTlvHexList ()(string, error) {
 //parameters: Count ExtendedHandle
 //AgtOspfOpaqueLsa GetTlvHexList
 return "", nil
}

