package n2xsdk

type OspfRouterLsa struct {
 Handler string
}

func(np *OspfRouterLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfRouterLsa SetAdvertisingRouter
 return nil
}

func(np *OspfRouterLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetAdvertisingRouter
 return "", nil
}

func(np *OspfRouterLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfRouterLsa SetLinkStateId
 return nil
}

func(np *OspfRouterLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetLinkStateId
 return "", nil
}

func(np *OspfRouterLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfRouterLsa SetOptions
 return nil
}

func(np *OspfRouterLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetOptions
 return "", nil
}

func(np *OspfRouterLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfRouterLsa SetLsType
 return nil
}

func(np *OspfRouterLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfRouterLsa GetLsType
 return "", nil
}

func(np *OspfRouterLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfRouterLsa Advertise
 return nil
}

func(np *OspfRouterLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfRouterLsa Withdraw
 return nil
}

func(np *OspfRouterLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetAdvertiseFlag
 return "", nil
}

func(np *OspfRouterLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfRouterLsa EnableAutoGenerate
 return nil
}

func(np *OspfRouterLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfRouterLsa DisableAutoGenerate
 return nil
}

func(np *OspfRouterLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfRouterLsa IsFieldAutoGenerated
 return nil
}

func(np *OspfRouterLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfRouterLsa SetChecksum
 return nil
}

func(np *OspfRouterLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetChecksum
 return "", nil
}

func(np *OspfRouterLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfRouterLsa SetLsAge
 return nil
}

func(np *OspfRouterLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetLsAge
 return "", nil
}

func(np *OspfRouterLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfRouterLsa SetSequenceNumber
 return nil
}

func(np *OspfRouterLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetSequenceNumber
 return "", nil
}

func(np *OspfRouterLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfRouterLsa EnableAutoUpdate
 return nil
}

func(np *OspfRouterLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfRouterLsa DisableAutoUpdate
 return nil
}

func(np *OspfRouterLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfRouterLsa IsAutoUpdateEnabled
 return nil
}

func(np *OspfRouterLsa) AddLink () error {
 //parameters: LsaHandle LinkId LinkData LinkType Metric
 //AgtOspfRouterLsa AddLink
 return nil
}

func(np *OspfRouterLsa) RemoveLink () error {
 //parameters: LsaHandle LinkIndex
 //AgtOspfRouterLsa RemoveLink
 return nil
}

func(np *OspfRouterLsa) GetNumberOfLinks ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetNumberOfLinks
 return "", nil
}

func(np *OspfRouterLsa) GetMaximumLinks ()(string, error) {
 //parameters: 
 //AgtOspfRouterLsa GetMaximumLinks
 return "", nil
}

func(np *OspfRouterLsa) GetLinkId ()(string, error) {
 //parameters: LsaHandle LinkIndex
 //AgtOspfRouterLsa GetLinkId
 return "", nil
}

func(np *OspfRouterLsa) SetLinkId () error {
 //parameters: LsaHandle LinkIndex LinkId
 //AgtOspfRouterLsa SetLinkId
 return nil
}

func(np *OspfRouterLsa) GetLinkData ()(string, error) {
 //parameters: LsaHandle LinkIndex
 //AgtOspfRouterLsa GetLinkData
 return "", nil
}

func(np *OspfRouterLsa) SetLinkData () error {
 //parameters: LsaHandle LinkIndex LinkData
 //AgtOspfRouterLsa SetLinkData
 return nil
}

func(np *OspfRouterLsa) GetLinkType ()(string, error) {
 //parameters: LsaHandle LinkIndex
 //AgtOspfRouterLsa GetLinkType
 return "", nil
}

func(np *OspfRouterLsa) SetLinkType () error {
 //parameters: LsaHandle LinkIndex LinkType
 //AgtOspfRouterLsa SetLinkType
 return nil
}

func(np *OspfRouterLsa) GetLinkMetric ()(string, error) {
 //parameters: LsaHandle LinkIndex
 //AgtOspfRouterLsa GetLinkMetric
 return "", nil
}

func(np *OspfRouterLsa) SetLinkMetric () error {
 //parameters: LsaHandle LinkIndex Metric
 //AgtOspfRouterLsa SetLinkMetric
 return nil
}

func(np *OspfRouterLsa) SetRouterType () error {
 //parameters: LsaHandle RouterTypeValue
 //AgtOspfRouterLsa SetRouterType
 return nil
}

func(np *OspfRouterLsa) GetRouterType ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetRouterType
 return "", nil
}

func(np *OspfRouterLsa) GetRouterLsaDetails ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfRouterLsa GetRouterLsaDetails
 return "", nil
}

func(np *OspfRouterLsa) GetLinkDetails ()(string, error) {
 //parameters: LsaHandle LinkIndex
 //AgtOspfRouterLsa GetLinkDetails
 return "", nil
}

