package n2xsdk

type Ospfv3IntraAreaPrefixLsa struct {
 Handler string
}

func(np *Ospfv3IntraAreaPrefixLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3IntraAreaPrefixLsa SetAdvertisingRouter, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetAdvertisingRouter
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfv3IntraAreaPrefixLsa SetLinkStateId, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetLinkStateId
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3IntraAreaPrefixLsa SetOptions, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetOptions
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfv3IntraAreaPrefixLsa SetLsType, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfv3IntraAreaPrefixLsa GetLsType
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa Advertise, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa Withdraw, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetAdvertiseFlag
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3IntraAreaPrefixLsa EnableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3IntraAreaPrefixLsa DisableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3IntraAreaPrefixLsa IsFieldAutoGenerated, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfv3IntraAreaPrefixLsa SetChecksum, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetChecksum
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfv3IntraAreaPrefixLsa SetLsAge, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetLsAge
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfv3IntraAreaPrefixLsa SetSequenceNumber, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetSequenceNumber
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa EnableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa DisableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa IsAutoUpdateEnabled, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) AddPrefix () error {
 //parameters: LsaHandle PrefixLength PrefixOptions Metric AddressPrefix
 //AgtOspfv3IntraAreaPrefixLsa AddPrefix, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) RemovePrefix () error {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3IntraAreaPrefixLsa RemovePrefix, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetNumberOfPrefixes ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetNumberOfPrefixes
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetMaximumPrefixes ()(string, error) {
 //parameters: 
 //AgtOspfv3IntraAreaPrefixLsa GetMaximumPrefixes
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetPrefixLength ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3IntraAreaPrefixLsa GetPrefixLength
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetPrefixLength () error {
 //parameters: LsaHandle PrefixIndex PrefixLength
 //AgtOspfv3IntraAreaPrefixLsa SetPrefixLength, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetPrefixOptions ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3IntraAreaPrefixLsa GetPrefixOptions
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetPrefixOptions () error {
 //parameters: LsaHandle PrefixIndex PrefixOptions
 //AgtOspfv3IntraAreaPrefixLsa SetPrefixOptions, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetAddressPrefix ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3IntraAreaPrefixLsa GetAddressPrefix
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetAddressPrefix () error {
 //parameters: LsaHandle PrefixIndex AddressPrefix
 //AgtOspfv3IntraAreaPrefixLsa SetAddressPrefix, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetMetric ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3IntraAreaPrefixLsa GetMetric
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetMetric () error {
 //parameters: LsaHandle PrefixIndex Metric
 //AgtOspfv3IntraAreaPrefixLsa SetMetric, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetReferencedLsType ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetReferencedLsType
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetReferencedLsType () error {
 //parameters: LsaHandle RefType
 //AgtOspfv3IntraAreaPrefixLsa SetReferencedLsType, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetReferencedLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetReferencedLinkStateId
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetReferencedLinkStateId () error {
 //parameters: LsaHandle RefLsId
 //AgtOspfv3IntraAreaPrefixLsa SetReferencedLinkStateId, m.Object, m.Name);
 return nil
}

func(np *Ospfv3IntraAreaPrefixLsa) GetReferencedAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3IntraAreaPrefixLsa GetReferencedAdvertisingRouter
 return "", nil
}

func(np *Ospfv3IntraAreaPrefixLsa) SetReferencedAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3IntraAreaPrefixLsa SetReferencedAdvertisingRouter, m.Object, m.Name);
 return nil
}

