package n2xsdk

type Ospfv3LinkLsa struct {
 Handler string
}

func(np *Ospfv3LinkLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3LinkLsa SetAdvertisingRouter
 return nil
}

func(np *Ospfv3LinkLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetAdvertisingRouter
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfv3LinkLsa SetLinkStateId
 return nil
}

func(np *Ospfv3LinkLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetLinkStateId
 return "", nil
}

func(np *Ospfv3LinkLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3LinkLsa SetOptions
 return nil
}

func(np *Ospfv3LinkLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetOptions
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfv3LinkLsa SetLsType
 return nil
}

func(np *Ospfv3LinkLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfv3LinkLsa GetLsType
 return "", nil
}

func(np *Ospfv3LinkLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa Advertise
 return nil
}

func(np *Ospfv3LinkLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa Withdraw
 return nil
}

func(np *Ospfv3LinkLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetAdvertiseFlag
 return "", nil
}

func(np *Ospfv3LinkLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3LinkLsa EnableAutoGenerate
 return nil
}

func(np *Ospfv3LinkLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3LinkLsa DisableAutoGenerate
 return nil
}

func(np *Ospfv3LinkLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3LinkLsa IsFieldAutoGenerated
 return nil
}

func(np *Ospfv3LinkLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfv3LinkLsa SetChecksum
 return nil
}

func(np *Ospfv3LinkLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetChecksum
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfv3LinkLsa SetLsAge
 return nil
}

func(np *Ospfv3LinkLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetLsAge
 return "", nil
}

func(np *Ospfv3LinkLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfv3LinkLsa SetSequenceNumber
 return nil
}

func(np *Ospfv3LinkLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetSequenceNumber
 return "", nil
}

func(np *Ospfv3LinkLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa EnableAutoUpdate
 return nil
}

func(np *Ospfv3LinkLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa DisableAutoUpdate
 return nil
}

func(np *Ospfv3LinkLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa IsAutoUpdateEnabled
 return nil
}

func(np *Ospfv3LinkLsa) AddPrefix () error {
 //parameters: LsaHandle PrefixLength PrefixOptions AddressPrefix
 //AgtOspfv3LinkLsa AddPrefix
 return nil
}

func(np *Ospfv3LinkLsa) RemovePrefix () error {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3LinkLsa RemovePrefix
 return nil
}

func(np *Ospfv3LinkLsa) GetNumberOfPrefixes ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetNumberOfPrefixes
 return "", nil
}

func(np *Ospfv3LinkLsa) GetMaximumPrefixes ()(string, error) {
 //parameters: 
 //AgtOspfv3LinkLsa GetMaximumPrefixes
 return "", nil
}

func(np *Ospfv3LinkLsa) GetPrefixLength ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3LinkLsa GetPrefixLength
 return "", nil
}

func(np *Ospfv3LinkLsa) SetPrefixLength () error {
 //parameters: LsaHandle PrefixIndex PrefixLength
 //AgtOspfv3LinkLsa SetPrefixLength
 return nil
}

func(np *Ospfv3LinkLsa) GetPrefixOptions ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3LinkLsa GetPrefixOptions
 return "", nil
}

func(np *Ospfv3LinkLsa) SetPrefixOptions () error {
 //parameters: LsaHandle PrefixIndex PrefixOptions
 //AgtOspfv3LinkLsa SetPrefixOptions
 return nil
}

func(np *Ospfv3LinkLsa) GetAddressPrefix ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3LinkLsa GetAddressPrefix
 return "", nil
}

func(np *Ospfv3LinkLsa) SetAddressPrefix () error {
 //parameters: LsaHandle PrefixIndex AddressPrefix
 //AgtOspfv3LinkLsa SetAddressPrefix
 return nil
}

func(np *Ospfv3LinkLsa) SetRouterPriority () error {
 //parameters: LsaHandle Priority
 //AgtOspfv3LinkLsa SetRouterPriority
 return nil
}

func(np *Ospfv3LinkLsa) GetRouterPriority ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetRouterPriority
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLinkLsaOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3LinkLsa SetLinkLsaOptions
 return nil
}

func(np *Ospfv3LinkLsa) GetLinkLsaOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetLinkLsaOptions
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLinkLocalInterfaceAddress () error {
 //parameters: LsaHandle InterfaceAddress
 //AgtOspfv3LinkLsa SetLinkLocalInterfaceAddress
 return nil
}

func(np *Ospfv3LinkLsa) GetLinkLocalInterfaceAddress ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetLinkLocalInterfaceAddress
 return "", nil
}

