package n2xsdk

type OspfOpaqueLsa2 struct {
 Handler string
}

func(np *OspfOpaqueLsa2) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfOpaqueLsa2 SetAdvertisingRouter
 return nil
}

func(np *OspfOpaqueLsa2) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 GetAdvertisingRouter
 return "", nil
}

func(np *OspfOpaqueLsa2) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfOpaqueLsa2 SetLinkStateId
 return nil
}

func(np *OspfOpaqueLsa2) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 GetLinkStateId
 return "", nil
}

func(np *OspfOpaqueLsa2) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfOpaqueLsa2 SetOptions
 return nil
}

func(np *OspfOpaqueLsa2) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 GetOptions
 return "", nil
}

func(np *OspfOpaqueLsa2) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfOpaqueLsa2 SetLsType
 return nil
}

func(np *OspfOpaqueLsa2) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfOpaqueLsa2 GetLsType
 return "", nil
}

func(np *OspfOpaqueLsa2) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 Advertise
 return nil
}

func(np *OspfOpaqueLsa2) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 Withdraw
 return nil
}

func(np *OspfOpaqueLsa2) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 GetAdvertiseFlag
 return "", nil
}

func(np *OspfOpaqueLsa2) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfOpaqueLsa2 EnableAutoGenerate
 return nil
}

func(np *OspfOpaqueLsa2) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfOpaqueLsa2 DisableAutoGenerate
 return nil
}

func(np *OspfOpaqueLsa2) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfOpaqueLsa2 IsFieldAutoGenerated
 return nil
}

func(np *OspfOpaqueLsa2) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfOpaqueLsa2 SetChecksum
 return nil
}

func(np *OspfOpaqueLsa2) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 GetChecksum
 return "", nil
}

func(np *OspfOpaqueLsa2) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfOpaqueLsa2 SetLsAge
 return nil
}

func(np *OspfOpaqueLsa2) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 GetLsAge
 return "", nil
}

func(np *OspfOpaqueLsa2) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfOpaqueLsa2 SetSequenceNumber
 return nil
}

func(np *OspfOpaqueLsa2) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 GetSequenceNumber
 return "", nil
}

func(np *OspfOpaqueLsa2) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 EnableAutoUpdate
 return nil
}

func(np *OspfOpaqueLsa2) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 DisableAutoUpdate
 return nil
}

func(np *OspfOpaqueLsa2) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 IsAutoUpdateEnabled
 return nil
}

func(np *OspfOpaqueLsa2) SetOpaqueLsaType () error {
 //parameters: LsaHandle LsaType
 //AgtOspfOpaqueLsa2 SetOpaqueLsaType
 return nil
}

func(np *OspfOpaqueLsa2) GetOpaqueLsaType ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 GetOpaqueLsaType
 return "", nil
}

func(np *OspfOpaqueLsa2) AddTlv () error {
 //parameters: LsaHandle TlvType
 //AgtOspfOpaqueLsa2 AddTlv
 return nil
}

func(np *OspfOpaqueLsa2) AddSubTlv () error {
 //parameters: LsaHandle Count TlvHandle TlvType
 //AgtOspfOpaqueLsa2 AddSubTlv
 return nil
}

func(np *OspfOpaqueLsa2) RemoveTlv () error {
 //parameters: LsaHandle Count TlvHandle
 //AgtOspfOpaqueLsa2 RemoveTlv
 return nil
}

func(np *OspfOpaqueLsa2) ListTlvs ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfOpaqueLsa2 ListTlvs
 return "", nil
}

func(np *OspfOpaqueLsa2) ListSubTlvs ()(string, error) {
 //parameters: LsaHandle Count TlvHandle
 //AgtOspfOpaqueLsa2 ListSubTlvs
 return "", nil
}

func(np *OspfOpaqueLsa2) GetTlvValueType ()(string, error) {
 //parameters: LsaHandle Count TlvHandle
 //AgtOspfOpaqueLsa2 GetTlvValueType
 return "", nil
}

func(np *OspfOpaqueLsa2) SetTlvIpv4Address () error {
 //parameters: LsaHandle Count TlvHandle Ipv4Address
 //AgtOspfOpaqueLsa2 SetTlvIpv4Address
 return nil
}

func(np *OspfOpaqueLsa2) GetTlvIpv4Address ()(string, error) {
 //parameters: LsaHandle Count TlvHandle
 //AgtOspfOpaqueLsa2 GetTlvIpv4Address
 return "", nil
}

func(np *OspfOpaqueLsa2) SetTlvLong () error {
 //parameters: LsaHandle Count TlvHandle Length LongValue
 //AgtOspfOpaqueLsa2 SetTlvLong
 return nil
}

func(np *OspfOpaqueLsa2) GetTlvLong ()(string, error) {
 //parameters: LsaHandle Count TlvHandle
 //AgtOspfOpaqueLsa2 GetTlvLong
 return "", nil
}

func(np *OspfOpaqueLsa2) SetTlvFloat () error {
 //parameters: LsaHandle Count TlvHandle aFloatValue
 //AgtOspfOpaqueLsa2 SetTlvFloat
 return nil
}

func(np *OspfOpaqueLsa2) GetTlvFloat ()(string, error) {
 //parameters: LsaHandle Count TlvHandle
 //AgtOspfOpaqueLsa2 GetTlvFloat
 return "", nil
}

func(np *OspfOpaqueLsa2) SetTlvFloatList ()(string, error) {
 //parameters: LsaHandle Count TlvHandle NumFloats aFloatList
 //AgtOspfOpaqueLsa2 SetTlvFloatList
 return "", nil
}

func(np *OspfOpaqueLsa2) GetTlvFloatList ()(string, error) {
 //parameters: LsaHandle Count TlvHandle
 //AgtOspfOpaqueLsa2 GetTlvFloatList
 return "", nil
}

func(np *OspfOpaqueLsa2) SetTlvHexList ()(string, error) {
 //parameters: LsaHandle Count TlvHandle NumOctets pHexList
 //AgtOspfOpaqueLsa2 SetTlvHexList
 return "", nil
}

func(np *OspfOpaqueLsa2) GetTlvHexList ()(string, error) {
 //parameters: LsaHandle Count TlvHandle
 //AgtOspfOpaqueLsa2 GetTlvHexList
 return "", nil
}

