package n2xsdk

type Ospfv3NetworkLsa struct {
 Handler string
}

func(np *Ospfv3NetworkLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3NetworkLsa SetAdvertisingRouter, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa GetAdvertisingRouter
 return "", nil
}

func(np *Ospfv3NetworkLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfv3NetworkLsa SetLinkStateId, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa GetLinkStateId
 return "", nil
}

func(np *Ospfv3NetworkLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3NetworkLsa SetOptions, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa GetOptions
 return "", nil
}

func(np *Ospfv3NetworkLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfv3NetworkLsa SetLsType, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfv3NetworkLsa GetLsType
 return "", nil
}

func(np *Ospfv3NetworkLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa Advertise, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa Withdraw, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa GetAdvertiseFlag
 return "", nil
}

func(np *Ospfv3NetworkLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3NetworkLsa EnableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3NetworkLsa DisableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3NetworkLsa IsFieldAutoGenerated, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfv3NetworkLsa SetChecksum, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa GetChecksum
 return "", nil
}

func(np *Ospfv3NetworkLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfv3NetworkLsa SetLsAge, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa GetLsAge
 return "", nil
}

func(np *Ospfv3NetworkLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfv3NetworkLsa SetSequenceNumber, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa GetSequenceNumber
 return "", nil
}

func(np *Ospfv3NetworkLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa EnableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa DisableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa IsAutoUpdateEnabled, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) SetNetworkLsaOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3NetworkLsa SetNetworkLsaOptions, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetNetworkLsaOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa GetNetworkLsaOptions
 return "", nil
}

func(np *Ospfv3NetworkLsa) AddAttachedRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3NetworkLsa AddAttachedRouter, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) RemoveAttachedRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3NetworkLsa RemoveAttachedRouter, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) ClearAttachedRouters () error {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa ClearAttachedRouters, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) ListAttachedRouters ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3NetworkLsa ListAttachedRouters
 return "", nil
}

func(np *Ospfv3NetworkLsa) GetMaximumAttachedRouters ()(string, error) {
 //parameters: 
 //AgtOspfv3NetworkLsa GetMaximumAttachedRouters
 return "", nil
}

func(np *Ospfv3NetworkLsa) SetAttachedRouterId () error {
 //parameters: LsaHandle RouterIndex RouterId
 //AgtOspfv3NetworkLsa SetAttachedRouterId, m.Object, m.Name);
 return nil
}

func(np *Ospfv3NetworkLsa) GetAttachedRouterId ()(string, error) {
 //parameters: LsaHandle RouterIndex
 //AgtOspfv3NetworkLsa GetAttachedRouterId
 return "", nil
}

