package n2xsdk

type OspfAsbrSummaryLsa struct {
 Handler string
}

func(np *OspfAsbrSummaryLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfAsbrSummaryLsa SetAdvertisingRouter, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa GetAdvertisingRouter
 return "", nil
}

func(np *OspfAsbrSummaryLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfAsbrSummaryLsa SetLinkStateId, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa GetLinkStateId
 return "", nil
}

func(np *OspfAsbrSummaryLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfAsbrSummaryLsa SetOptions, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa GetOptions
 return "", nil
}

func(np *OspfAsbrSummaryLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfAsbrSummaryLsa SetLsType, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfAsbrSummaryLsa GetLsType
 return "", nil
}

func(np *OspfAsbrSummaryLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa Advertise, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa Withdraw, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa GetAdvertiseFlag
 return "", nil
}

func(np *OspfAsbrSummaryLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfAsbrSummaryLsa EnableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfAsbrSummaryLsa DisableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfAsbrSummaryLsa IsFieldAutoGenerated, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfAsbrSummaryLsa SetChecksum, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa GetChecksum
 return "", nil
}

func(np *OspfAsbrSummaryLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfAsbrSummaryLsa SetLsAge, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa GetLsAge
 return "", nil
}

func(np *OspfAsbrSummaryLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfAsbrSummaryLsa SetSequenceNumber, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa GetSequenceNumber
 return "", nil
}

func(np *OspfAsbrSummaryLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa EnableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa DisableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa IsAutoUpdateEnabled, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) SetMetric () error {
 //parameters: LsaHandle Metric
 //AgtOspfAsbrSummaryLsa SetMetric, m.Object, m.Name);
 return nil
}

func(np *OspfAsbrSummaryLsa) GetMetric ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfAsbrSummaryLsa GetMetric
 return "", nil
}

