package n2xsdk

type Ospfv3LinkLsa struct {
 Handler string
}

func(np *Ospfv3LinkLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3LinkLsa SetAdvertisingRouter, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetAdvertisingRouter
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfv3LinkLsa SetLinkStateId, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetLinkStateId
 return "", nil
}

func(np *Ospfv3LinkLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3LinkLsa SetOptions, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetOptions
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfv3LinkLsa SetLsType, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfv3LinkLsa GetLsType
 return "", nil
}

func(np *Ospfv3LinkLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa Advertise, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa Withdraw, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetAdvertiseFlag
 return "", nil
}

func(np *Ospfv3LinkLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3LinkLsa EnableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3LinkLsa DisableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3LinkLsa IsFieldAutoGenerated, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfv3LinkLsa SetChecksum, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetChecksum
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfv3LinkLsa SetLsAge, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetLsAge
 return "", nil
}

func(np *Ospfv3LinkLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfv3LinkLsa SetSequenceNumber, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetSequenceNumber
 return "", nil
}

func(np *Ospfv3LinkLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa EnableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa DisableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa IsAutoUpdateEnabled, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) AddPrefix () error {
 //parameters: LsaHandle PrefixLength PrefixOptions AddressPrefix
 //AgtOspfv3LinkLsa AddPrefix, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) RemovePrefix () error {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3LinkLsa RemovePrefix, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetNumberOfPrefixes ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetNumberOfPrefixes
 return "", nil
}

func(np *Ospfv3LinkLsa) GetMaximumPrefixes ()(string, error) {
 //parameters: 
 //AgtOspfv3LinkLsa GetMaximumPrefixes
 return "", nil
}

func(np *Ospfv3LinkLsa) GetPrefixLength ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3LinkLsa GetPrefixLength
 return "", nil
}

func(np *Ospfv3LinkLsa) SetPrefixLength () error {
 //parameters: LsaHandle PrefixIndex PrefixLength
 //AgtOspfv3LinkLsa SetPrefixLength, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetPrefixOptions ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3LinkLsa GetPrefixOptions
 return "", nil
}

func(np *Ospfv3LinkLsa) SetPrefixOptions () error {
 //parameters: LsaHandle PrefixIndex PrefixOptions
 //AgtOspfv3LinkLsa SetPrefixOptions, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetAddressPrefix ()(string, error) {
 //parameters: LsaHandle PrefixIndex
 //AgtOspfv3LinkLsa GetAddressPrefix
 return "", nil
}

func(np *Ospfv3LinkLsa) SetAddressPrefix () error {
 //parameters: LsaHandle PrefixIndex AddressPrefix
 //AgtOspfv3LinkLsa SetAddressPrefix, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) SetRouterPriority () error {
 //parameters: LsaHandle Priority
 //AgtOspfv3LinkLsa SetRouterPriority, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetRouterPriority ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetRouterPriority
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLinkLsaOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3LinkLsa SetLinkLsaOptions, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetLinkLsaOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetLinkLsaOptions
 return "", nil
}

func(np *Ospfv3LinkLsa) SetLinkLocalInterfaceAddress () error {
 //parameters: LsaHandle InterfaceAddress
 //AgtOspfv3LinkLsa SetLinkLocalInterfaceAddress, m.Object, m.Name);
 return nil
}

func(np *Ospfv3LinkLsa) GetLinkLocalInterfaceAddress ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3LinkLsa GetLinkLocalInterfaceAddress
 return "", nil
}

