package n2xsdk

type OspfTeLinkLsa struct {
 Handler string
}

func(np *OspfTeLinkLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfTeLinkLsa SetAdvertisingRouter, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetAdvertisingRouter
 return "", nil
}

func(np *OspfTeLinkLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfTeLinkLsa SetLinkStateId, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetLinkStateId
 return "", nil
}

func(np *OspfTeLinkLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfTeLinkLsa SetOptions, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetOptions
 return "", nil
}

func(np *OspfTeLinkLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfTeLinkLsa SetLsType, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfTeLinkLsa GetLsType
 return "", nil
}

func(np *OspfTeLinkLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa Advertise, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa Withdraw, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetAdvertiseFlag
 return "", nil
}

func(np *OspfTeLinkLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfTeLinkLsa EnableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfTeLinkLsa DisableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfTeLinkLsa IsFieldAutoGenerated, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfTeLinkLsa SetChecksum, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetChecksum
 return "", nil
}

func(np *OspfTeLinkLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfTeLinkLsa SetLsAge, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetLsAge
 return "", nil
}

func(np *OspfTeLinkLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfTeLinkLsa SetSequenceNumber, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetSequenceNumber
 return "", nil
}

func(np *OspfTeLinkLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa EnableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa DisableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa IsAutoUpdateEnabled, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) EnableGmplsBehavior () error {
 //parameters: hLsa
 //AgtOspfTeLinkLsa EnableGmplsBehavior, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) DisableGmplsBehavior () error {
 //parameters: hLsa
 //AgtOspfTeLinkLsa DisableGmplsBehavior, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) IsGmplsBehaviorEnabled () error {
 //parameters: hLsa
 //AgtOspfTeLinkLsa IsGmplsBehaviorEnabled, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) SetSubTlvString () error {
 //parameters: LsaHandle eType Value
 //AgtOspfTeLinkLsa SetSubTlvString, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetSubTlvString ()(string, error) {
 //parameters: LsaHandle eType
 //AgtOspfTeLinkLsa GetSubTlvString
 return "", nil
}

func(np *OspfTeLinkLsa) SetLinkType () error {
 //parameters: LsaHandle Value
 //AgtOspfTeLinkLsa SetLinkType, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetLinkType ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetLinkType
 return "", nil
}

func(np *OspfTeLinkLsa) SetLinkNumbered () error {
 //parameters: LsaHandle bNumbered
 //AgtOspfTeLinkLsa SetLinkNumbered, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetLinkNumbered ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetLinkNumbered
 return "", nil
}

func(np *OspfTeLinkLsa) SetLinkId () error {
 //parameters: LsaHandle Value
 //AgtOspfTeLinkLsa SetLinkId, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetLinkId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetLinkId
 return "", nil
}

func(np *OspfTeLinkLsa) SetLocalInterfaceAddress () error {
 //parameters: LsaHandle Value
 //AgtOspfTeLinkLsa SetLocalInterfaceAddress, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetLocalInterfaceAddress ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetLocalInterfaceAddress
 return "", nil
}

func(np *OspfTeLinkLsa) SetRemoteInterfaceAddress () error {
 //parameters: LsaHandle Value
 //AgtOspfTeLinkLsa SetRemoteInterfaceAddress, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetRemoteInterfaceAddress ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetRemoteInterfaceAddress
 return "", nil
}

func(np *OspfTeLinkLsa) SetTeMetric () error {
 //parameters: LsaHandle LongValue
 //AgtOspfTeLinkLsa SetTeMetric, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetTeMetric ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetTeMetric
 return "", nil
}

func(np *OspfTeLinkLsa) SetMaxLinkBandwidth () error {
 //parameters: LsaHandle FloatValue
 //AgtOspfTeLinkLsa SetMaxLinkBandwidth, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetMaxLinkBandwidth ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetMaxLinkBandwidth
 return "", nil
}

func(np *OspfTeLinkLsa) SetMaxReservableBandwidth () error {
 //parameters: LsaHandle FloatValue
 //AgtOspfTeLinkLsa SetMaxReservableBandwidth, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetMaxReservableBandwidth ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetMaxReservableBandwidth
 return "", nil
}

func(np *OspfTeLinkLsa) SetUnreservedBandwidth () error {
 //parameters: LsaHandle Count psaValues
 //AgtOspfTeLinkLsa SetUnreservedBandwidth, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetUnreservedBandwidth ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeLinkLsa GetUnreservedBandwidth
 return "", nil
}

func(np *OspfTeLinkLsa) SetResourceClass () error {
 //parameters: LsaHandle LongValue
 //AgtOspfTeLinkLsa SetResourceClass, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetResourceClass ()(string, error) {
 //parameters: hLsaHandle
 //AgtOspfTeLinkLsa GetResourceClass
 return "", nil
}

func(np *OspfTeLinkLsa) SetLinkIdentifiers () error {
 //parameters: hLsa Local Remote
 //AgtOspfTeLinkLsa SetLinkIdentifiers, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetLinkIdentifiers ()(string, error) {
 //parameters: hLsa
 //AgtOspfTeLinkLsa GetLinkIdentifiers
 return "", nil
}

func(np *OspfTeLinkLsa) SetLinkProtectionType () error {
 //parameters: hLsa Value
 //AgtOspfTeLinkLsa SetLinkProtectionType, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetLinkProtectionType ()(string, error) {
 //parameters: hLsa
 //AgtOspfTeLinkLsa GetLinkProtectionType
 return "", nil
}

func(np *OspfTeLinkLsa) SetSwitchingCapability () error {
 //parameters: hLsa SwitchingCapability LspEncode Count psaMaxBandwidth
 //AgtOspfTeLinkLsa SetSwitchingCapability, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) SetSwitchingCapabilityWithSpecificInfo () error {
 //parameters: hLsa SwitchingCapability LspEncode MinLspBandwidth Indication Count psaMaxBandwidth
 //AgtOspfTeLinkLsa SetSwitchingCapabilityWithSpecificInfo, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetSwitchingCapability ()(string, error) {
 //parameters: hLsa
 //AgtOspfTeLinkLsa GetSwitchingCapability
 return "", nil
}

func(np *OspfTeLinkLsa) SetSharedRiskLinkGroup () error {
 //parameters: hLsa Count psaLinkGroup
 //AgtOspfTeLinkLsa SetSharedRiskLinkGroup, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetSharedRiskLinkGroup ()(string, error) {
 //parameters: hLsa
 //AgtOspfTeLinkLsa GetSharedRiskLinkGroup
 return "", nil
}

func(np *OspfTeLinkLsa) SetSubTlvLong () error {
 //parameters: LsaHandle eType LongValue
 //AgtOspfTeLinkLsa SetSubTlvLong, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetSubTlvLong ()(string, error) {
 //parameters: LsaHandle eType
 //AgtOspfTeLinkLsa GetSubTlvLong
 return "", nil
}

func(np *OspfTeLinkLsa) SetSubTlvFloat () error {
 //parameters: LsaHandle eType FloatValue
 //AgtOspfTeLinkLsa SetSubTlvFloat, m.Object, m.Name);
 return nil
}

func(np *OspfTeLinkLsa) GetSubTlvFloat ()(string, error) {
 //parameters: LsaHandle eType
 //AgtOspfTeLinkLsa GetSubTlvFloat
 return "", nil
}

