package n2xsdk

type Ospfv3InterAreaRouterLsa struct {
 Handler string
}

func(np *Ospfv3InterAreaRouterLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3InterAreaRouterLsa SetAdvertisingRouter, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetAdvertisingRouter
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfv3InterAreaRouterLsa SetLinkStateId, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetLinkStateId
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3InterAreaRouterLsa SetOptions, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetOptions
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfv3InterAreaRouterLsa SetLsType, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfv3InterAreaRouterLsa GetLsType
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa Advertise, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa Withdraw, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetAdvertiseFlag
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3InterAreaRouterLsa EnableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3InterAreaRouterLsa DisableAutoGenerate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3InterAreaRouterLsa IsFieldAutoGenerated, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfv3InterAreaRouterLsa SetChecksum, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetChecksum
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfv3InterAreaRouterLsa SetLsAge, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetLsAge
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfv3InterAreaRouterLsa SetSequenceNumber, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetSequenceNumber
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa EnableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa DisableAutoUpdate, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa IsAutoUpdateEnabled, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) SetInterAreaRouterLsaOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3InterAreaRouterLsa SetInterAreaRouterLsaOptions, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetInterAreaRouterLsaOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetInterAreaRouterLsaOptions
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) GetMetric ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetMetric
 return "", nil
}

func(np *Ospfv3InterAreaRouterLsa) SetMetric () error {
 //parameters: LsaHandle Metric
 //AgtOspfv3InterAreaRouterLsa SetMetric, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) SetDestinationRouterId () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3InterAreaRouterLsa SetDestinationRouterId, m.Object, m.Name);
 return nil
}

func(np *Ospfv3InterAreaRouterLsa) GetDestinationRouterId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3InterAreaRouterLsa GetDestinationRouterId
 return "", nil
}

