package n2xsdk

type Ospfv3RouterLsa struct {
 Handler string
}

func(np *Ospfv3RouterLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfv3RouterLsa SetAdvertisingRouter
 return nil
}

func(np *Ospfv3RouterLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetAdvertisingRouter
 return "", nil
}

func(np *Ospfv3RouterLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfv3RouterLsa SetLinkStateId
 return nil
}

func(np *Ospfv3RouterLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetLinkStateId
 return "", nil
}

func(np *Ospfv3RouterLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3RouterLsa SetOptions
 return nil
}

func(np *Ospfv3RouterLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetOptions
 return "", nil
}

func(np *Ospfv3RouterLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfv3RouterLsa SetLsType
 return nil
}

func(np *Ospfv3RouterLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfv3RouterLsa GetLsType
 return "", nil
}

func(np *Ospfv3RouterLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa Advertise
 return nil
}

func(np *Ospfv3RouterLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa Withdraw
 return nil
}

func(np *Ospfv3RouterLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetAdvertiseFlag
 return "", nil
}

func(np *Ospfv3RouterLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3RouterLsa EnableAutoGenerate
 return nil
}

func(np *Ospfv3RouterLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3RouterLsa DisableAutoGenerate
 return nil
}

func(np *Ospfv3RouterLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfv3RouterLsa IsFieldAutoGenerated
 return nil
}

func(np *Ospfv3RouterLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfv3RouterLsa SetChecksum
 return nil
}

func(np *Ospfv3RouterLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetChecksum
 return "", nil
}

func(np *Ospfv3RouterLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfv3RouterLsa SetLsAge
 return nil
}

func(np *Ospfv3RouterLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetLsAge
 return "", nil
}

func(np *Ospfv3RouterLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfv3RouterLsa SetSequenceNumber
 return nil
}

func(np *Ospfv3RouterLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetSequenceNumber
 return "", nil
}

func(np *Ospfv3RouterLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa EnableAutoUpdate
 return nil
}

func(np *Ospfv3RouterLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa DisableAutoUpdate
 return nil
}

func(np *Ospfv3RouterLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa IsAutoUpdateEnabled
 return nil
}

func(np *Ospfv3RouterLsa) SetRouterType () error {
 //parameters: LsaHandle RouterTypeValue
 //AgtOspfv3RouterLsa SetRouterType
 return nil
}

func(np *Ospfv3RouterLsa) GetRouterType ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetRouterType
 return "", nil
}

func(np *Ospfv3RouterLsa) AddInterface () error {
 //parameters: LsaHandle InterfaceId NeighborInterfaceId NeighborRouterId InterfaceType Metric
 //AgtOspfv3RouterLsa AddInterface
 return nil
}

func(np *Ospfv3RouterLsa) RemoveInterface () error {
 //parameters: LsaHandle InterfaceIndex
 //AgtOspfv3RouterLsa RemoveInterface
 return nil
}

func(np *Ospfv3RouterLsa) GetNumberOfInterfaces ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetNumberOfInterfaces
 return "", nil
}

func(np *Ospfv3RouterLsa) GetMaximumInterfaces ()(string, error) {
 //parameters: 
 //AgtOspfv3RouterLsa GetMaximumInterfaces
 return "", nil
}

func(np *Ospfv3RouterLsa) GetInterfaceIndex ()(string, error) {
 //parameters: LsaHandle OtherObjectHandle
 //AgtOspfv3RouterLsa GetInterfaceIndex
 return "", nil
}

func(np *Ospfv3RouterLsa) GetInterfaceId ()(string, error) {
 //parameters: LsaHandle InterfaceIndex
 //AgtOspfv3RouterLsa GetInterfaceId
 return "", nil
}

func(np *Ospfv3RouterLsa) SetInterfaceId () error {
 //parameters: LsaHandle InterfaceIndex InterfaceId
 //AgtOspfv3RouterLsa SetInterfaceId
 return nil
}

func(np *Ospfv3RouterLsa) GetNeighborInterfaceId ()(string, error) {
 //parameters: LsaHandle InterfaceIndex
 //AgtOspfv3RouterLsa GetNeighborInterfaceId
 return "", nil
}

func(np *Ospfv3RouterLsa) SetNeighborInterfaceId () error {
 //parameters: LsaHandle InterfaceIndex NeighborInterfaceId
 //AgtOspfv3RouterLsa SetNeighborInterfaceId
 return nil
}

func(np *Ospfv3RouterLsa) GetNeighborRouterId ()(string, error) {
 //parameters: LsaHandle InterfaceIndex
 //AgtOspfv3RouterLsa GetNeighborRouterId
 return "", nil
}

func(np *Ospfv3RouterLsa) SetNeighborRouterId () error {
 //parameters: LsaHandle InterfaceIndex NeighborRouterId
 //AgtOspfv3RouterLsa SetNeighborRouterId
 return nil
}

func(np *Ospfv3RouterLsa) GetInterfaceType ()(string, error) {
 //parameters: LsaHandle InterfaceIndex
 //AgtOspfv3RouterLsa GetInterfaceType
 return "", nil
}

func(np *Ospfv3RouterLsa) SetInterfaceType () error {
 //parameters: LsaHandle InterfaceIndex InterfaceType
 //AgtOspfv3RouterLsa SetInterfaceType
 return nil
}

func(np *Ospfv3RouterLsa) GetInterfaceMetric ()(string, error) {
 //parameters: LsaHandle InterfaceIndex
 //AgtOspfv3RouterLsa GetInterfaceMetric
 return "", nil
}

func(np *Ospfv3RouterLsa) SetInterfaceMetric () error {
 //parameters: LsaHandle InterfaceIndex Metric
 //AgtOspfv3RouterLsa SetInterfaceMetric
 return nil
}

func(np *Ospfv3RouterLsa) SetRouterLsaOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfv3RouterLsa SetRouterLsaOptions
 return nil
}

func(np *Ospfv3RouterLsa) GetRouterLsaOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfv3RouterLsa GetRouterLsaOptions
 return "", nil
}

