package n2xsdk

type OspfTeRouterLsa struct {
 Handler string
}

func(np *OspfTeRouterLsa) SetAdvertisingRouter () error {
 //parameters: LsaHandle RouterId
 //AgtOspfTeRouterLsa SetAdvertisingRouter
 return nil
}

func(np *OspfTeRouterLsa) GetAdvertisingRouter ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa GetAdvertisingRouter
 return "", nil
}

func(np *OspfTeRouterLsa) SetLinkStateId () error {
 //parameters: LsaHandle LinkStateId
 //AgtOspfTeRouterLsa SetLinkStateId
 return nil
}

func(np *OspfTeRouterLsa) GetLinkStateId ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa GetLinkStateId
 return "", nil
}

func(np *OspfTeRouterLsa) SetOptions () error {
 //parameters: LsaHandle Options
 //AgtOspfTeRouterLsa SetOptions
 return nil
}

func(np *OspfTeRouterLsa) GetOptions ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa GetOptions
 return "", nil
}

func(np *OspfTeRouterLsa) SetLsType () error {
 //parameters: LsaHandle Field Value
 //AgtOspfTeRouterLsa SetLsType
 return nil
}

func(np *OspfTeRouterLsa) GetLsType ()(string, error) {
 //parameters: LsaHandle Field
 //AgtOspfTeRouterLsa GetLsType
 return "", nil
}

func(np *OspfTeRouterLsa) Advertise () error {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa Advertise
 return nil
}

func(np *OspfTeRouterLsa) Withdraw () error {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa Withdraw
 return nil
}

func(np *OspfTeRouterLsa) GetAdvertiseFlag ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa GetAdvertiseFlag
 return "", nil
}

func(np *OspfTeRouterLsa) EnableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfTeRouterLsa EnableAutoGenerate
 return nil
}

func(np *OspfTeRouterLsa) DisableAutoGenerate () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfTeRouterLsa DisableAutoGenerate
 return nil
}

func(np *OspfTeRouterLsa) IsFieldAutoGenerated () error {
 //parameters: LsaHandle HeaderField
 //AgtOspfTeRouterLsa IsFieldAutoGenerated
 return nil
}

func(np *OspfTeRouterLsa) SetChecksum () error {
 //parameters: LsaHandle Checksum
 //AgtOspfTeRouterLsa SetChecksum
 return nil
}

func(np *OspfTeRouterLsa) GetChecksum ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa GetChecksum
 return "", nil
}

func(np *OspfTeRouterLsa) SetLsAge () error {
 //parameters: LsaHandle LsAge
 //AgtOspfTeRouterLsa SetLsAge
 return nil
}

func(np *OspfTeRouterLsa) GetLsAge ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa GetLsAge
 return "", nil
}

func(np *OspfTeRouterLsa) SetSequenceNumber () error {
 //parameters: LsaHandle SeqNum
 //AgtOspfTeRouterLsa SetSequenceNumber
 return nil
}

func(np *OspfTeRouterLsa) GetSequenceNumber ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa GetSequenceNumber
 return "", nil
}

func(np *OspfTeRouterLsa) EnableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa EnableAutoUpdate
 return nil
}

func(np *OspfTeRouterLsa) DisableAutoUpdate () error {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa DisableAutoUpdate
 return nil
}

func(np *OspfTeRouterLsa) IsAutoUpdateEnabled () error {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa IsAutoUpdateEnabled
 return nil
}

func(np *OspfTeRouterLsa) SetRouterAddress () error {
 //parameters: LsaHandle Value
 //AgtOspfTeRouterLsa SetRouterAddress
 return nil
}

func(np *OspfTeRouterLsa) GetRouterAddress ()(string, error) {
 //parameters: LsaHandle
 //AgtOspfTeRouterLsa GetRouterAddress
 return "", nil
}

