#!/bin/sh
if [ $# -eq 0 ]; then
    echo "Usage: fput FILENAME"
    exit 0;
fi
echo $PWD
echo $1
path="$1"
dir=${path%/*}
file=`echo $1 | awk -F / '{ print $NF; }'`

if [ $dir == $file ]; then
    dir=$PWD
fi

echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo "Starting uploading file: \"$file\" to File server!"
echo 
ftp -n << EOF
open 10.71.1.3
user tsl tsl
bi
lcd $dir
hash
put $file
bye
EOF
echo 
echo "Uploading file: \"$file\" to File server finished!"
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
